rerun-triggers: ['mtime', 'params', 'input', 'software-env', 'code']
notemp: true
local-cores: 6
latency-wait: 180
max-jobs-per-second: 10
keep-going: true
printshellcmds: true
resources: 'network_connections=3'
default-resources:
  - 'mem_gb=8'
  - 'disk=10'
  - 'walltime_hr=1'
  - 'walltime_min=00'
  - 'walltime_sec=00'
  - 'outdir="log/"'
use-conda: true
conda-frontend: 'conda'
use-singularity: false
jobscript: 'profiles/wynton-qsub/jobscript.sh'
cluster: "qsub -cwd \
        -v PATH \
        -pe smp {threads} \
        -l mem_free={resources.mem_gb}G \
        -l arch=lx-amd64 \
        -l scratch={resources.disk}G \
        -l h_rt={resources.walltime_hr}:{resources.walltime_min}:{resources.walltime_sec} \
        -j yes \
        -terse \
        -o {resources.outdir} \
        "
cluster-cancel: '/opt/sge/bin/lx-amd64/qdel'
jobname: '{name}.{jobid}.snkjb.sh'
config:
  - 'USE_CUDA=0'
  - 'MAX_THREADS=24'
